# -*- coding: utf-8 -*-
"""Data_Preprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xcMjKZsqZK8Ll5ZlV9fdH4ckxfudJJvz

# Import Library dan DataSet
"""

import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import load_model
from tensorflow.keras.optimizers import Adam
from google.colab import files
import matplotlib.pyplot as plt
import seaborn as sns
dataset = pd.read_csv("/content/DATARUMAH.csv")

"""# Data Pre-Processing"""

print('Shape dataset:', dataset.shape)
print('\nLima data teratas:\n', dataset.head())
print('\nInformasi dataset:')
print(dataset.info())
print('\nStatistik deskriptif:\n', dataset.describe())

print('\nLima data teratas:\n', dataset.head())

#Melihat Korelasi Antar Kolom
dataset_corr = dataset.corr()
print('Korelasi dataset:\n', dataset.corr())

color = sns.light_palette("green")
sns.heatmap(dataset_corr, annot=True, cmap=color)

#checking missing value antar kolom  
print(dataset.isnull().sum())
#Menghitung total missing value
print(dataset.isnull().sum().sum())

print(dataset.dropna())

# Q1, Q3, dan IQR
Q1 = dataset['HARGA'].quantile(0.25)
Q3 = dataset['HARGA'].quantile(0.75)
IQR = Q3 - Q1

# Check ukuran (baris dan kolom) sebelum data yang outliers dibuang
print('Shape awal: ', dataset.shape)

# Menghapus outliers
dataset = dataset[~((dataset['HARGA'] < (Q1 - 1.5 * IQR)) | (dataset['HARGA'] > (Q3 + 1.5 * IQR)))]

# Check ukuran (baris dan kolom) setelah data yang outliers dibuang
print('Shape akhir: ', dataset.shape)

from google.colab import files

dataset.to_csv('dataset_clean.csv')